services:
    frontend:
        build:
            context: .
            target: frontend
        image: consistentlee/vod_next:latest
        ports:
            - '127.0.0.1:3000:3000'
        environment:
            - NODE_ENV=production
            - API_BASE_URL=http://backend:8888
        depends_on:
            - backend

    backend:
        build:
            context: .
            target: backend
        image: consistentlee/vod_hub:latest
        ports:
            - '127.0.0.1:8888:8888'
        environment:
            - NODE_ENV=production