import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const routesDir = path.join(__dirname, '..', 'src', 'routes');
const outputPath = path.join(routesDir, 'registry.gen.ts');

function toCamelCase(str: string) {
    return str.replace(/[-_](.)/g, (_, c) => c.toUpperCase());
}

const dirs = fs
    .readdirSync(routesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

const imports: string[] = [];
const providerEntries: string[] = [];

for (const dir of dirs) {
    const dirPath = path.join(routesDir, dir);
    const files = fs.readdirSync(dirPath);
    const hasIndex = files.includes('index.ts');
    const safeName = toCamelCase(dir);

    const nsAlias = `ns${safeName.charAt(0).toUpperCase() + safeName.slice(1)}Namespace`;
    imports.push(`import { namespace as ${nsAlias} } from './${dir}/namespace';`);

    if (hasIndex) {
        const routesAlias = `ns${safeName.charAt(0).toUpperCase() + safeName.slice(1)}Routes`;
        imports.push(`import { routes as ${routesAlias} } from './${dir}';`);
        providerEntries.push(`    { name: '${dir}', namespace: ${nsAlias}, routes: ${routesAlias} }`);
    } else {
        const routeFiles = files.filter((f) => f.endsWith('.ts') && f !== 'namespace.ts' && f !== 'index.ts' && f !== 'request.ts' && f !== 'utils.ts' && !f.endsWith('.d.ts'));
        const routeAliases: string[] = [];
        for (const file of routeFiles) {
            const routeName = toCamelCase(file.replace(/\.ts$/, ''));
            const alias = `ns${safeName.charAt(0).toUpperCase() + safeName.slice(1)}${routeName.charAt(0).toUpperCase() + routeName.slice(1)}Route`;
            imports.push(`import { route as ${alias} } from './${dir}/${file.replace(/\.ts$/, '')}';`);
            routeAliases.push(alias);
        }
        providerEntries.push(`    { name: '${dir}', namespace: ${nsAlias}, routes: [${routeAliases.join(', ')}] }`);
    }
}

const output = `// AUTO-GENERATED by scripts/gen-routes.ts — DO NOT EDIT
${imports.join('\n')}

import { Hono, type Handler } from 'hono';

import type { Namespace, Route } from '@/types';

interface Provider {
    name: string;
    namespace: Namespace;
    routes: Route[] | { routes: Route[] };
}

const providers: Provider[] = [
${providerEntries.join(',\n')}
];

const namespaces: Record<
    string,
    Namespace & {
        routes: Record<
            string,
            Route & {
                location: string;
            }
        >;
    }
> = {};

for (const provider of providers) {
    const ns = provider.namespace;
    namespaces[provider.name] = {
        ...ns,
        routes: {
            ...namespaces[provider.name]?.routes
        }
    };

    const routeList: Route[] = Array.isArray(provider.routes)
        ? provider.routes
        : (provider.routes as { routes: Route[] }).routes;

    for (const route of routeList) {
        const paths = Array.isArray(route.path) ? route.path : [route.path];
        for (const p of paths) {
            namespaces[provider.name].routes[p] = {
                ...route,
                location: ''
            };
        }
    }
}

export { namespaces };

const app = new Hono();

Object.entries(namespaces).forEach(([namespace, namespaceContent]) => {
    const subApp = app.basePath(\`/\${namespace}\`);
    Object.entries(namespaceContent.routes).forEach(([routePath, route]) => {
        const wrappedHandler: Handler = async (ctx) => {
            if (!ctx.get('data')) {
                ctx.set('data', await route.handler(ctx));
            }
        };
        if (route.method === 'POST') {
            subApp.post(routePath, wrappedHandler);
        } else {
            subApp.get(routePath, wrappedHandler);
        }
    });
});

export default app;
`;

fs.writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated: ${outputPath}`);
console.log(`Providers: ${providerEntries.length}`);
