name: Dependency Review

on:
    pull_request:
        branches: [main]

jobs:
    review:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: 检查代码
              uses: actions/checkout@v6

            - name: 依赖变更审查
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: high
                  comment-summary-in-pr: always
